// <auto-generated />
using ConFutureNce.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace ConFutureNce.Migrations
{
    [DbContext(typeof(ConFutureNceContext))]
    [Migration("20180525215442_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConFutureNce.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("Address");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("ConferenceName")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("ConferenceName");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ConFutureNce.Models.Conference", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("AssignDeadline");

                    b.Property<DateTime?>("EndDate");

                    b.Property<DateTime?>("PaperDeadline");

                    b.Property<DateTime?>("ReviewDeadline");

                    b.Property<DateTime?>("SelectionDeadline");

                    b.Property<DateTime?>("StartDate");

                    b.HasKey("Name");

                    b.ToTable("Conference");
                });

            modelBuilder.Entity("ConFutureNce.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BillingAddress")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("PaymentId");

                    b.Property<string>("TaxNumber")
                        .IsRequired();

                    b.HasKey("InvoiceId");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("ConFutureNce.Models.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LanguageName");

                    b.HasKey("LanguageId");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("ConFutureNce.Models.Paper", b =>
                {
                    b.Property<int>("PaperId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abstract");

                    b.Property<int>("AuthorId");

                    b.Property<string>("Authors");

                    b.Property<int>("LanguageId");

                    b.Property<string>("OrgName");

                    b.Property<byte[]>("PaperFile");

                    b.Property<int?>("ReviewerId");

                    b.Property<DateTime>("SubmissionDate");

                    b.Property<string>("TitleENG");

                    b.Property<string>("TitleORG");

                    b.HasKey("PaperId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Paper");
                });

            modelBuilder.Entity("ConFutureNce.Models.PaperKeyword", b =>
                {
                    b.Property<string>("KeyWord");

                    b.Property<int>("PaperId");

                    b.HasKey("KeyWord", "PaperId");

                    b.HasIndex("PaperId");

                    b.ToTable("PaperKeyword");
                });

            modelBuilder.Entity("ConFutureNce.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDone");

                    b.Property<int>("PaperId");

                    b.HasKey("PaymentId");

                    b.HasIndex("PaperId")
                        .IsUnique();

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("ConFutureNce.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Achievements")
                        .IsRequired();

                    b.Property<DateTime>("Date");

                    b.Property<string>("GeneralComments");

                    b.Property<string>("Grade")
                        .IsRequired();

                    b.Property<string>("NotMentioned")
                        .IsRequired();

                    b.Property<int>("PaperId");

                    b.Property<string>("Problems")
                        .IsRequired();

                    b.Property<string>("Solution")
                        .IsRequired();

                    b.Property<string>("WhyProblems")
                        .IsRequired();

                    b.HasKey("ReviewId");

                    b.HasIndex("PaperId")
                        .IsUnique();

                    b.ToTable("Review");
                });

            modelBuilder.Entity("ConFutureNce.Models.UserType", b =>
                {
                    b.Property<int>("UserTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationUserId")
                        .IsRequired();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("UserTypeId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("UserType");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UserType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ConFutureNce.Models.Author", b =>
                {
                    b.HasBaseType("ConFutureNce.Models.UserType");

                    b.Property<string>("OrgName")
                        .IsRequired();

                    b.Property<string>("ScTitle")
                        .IsRequired();

                    b.ToTable("Author");

                    b.HasDiscriminator().HasValue("Author");
                });

            modelBuilder.Entity("ConFutureNce.Models.Organizer", b =>
                {
                    b.HasBaseType("ConFutureNce.Models.UserType");

                    b.Property<string>("EmployeePosition");

                    b.ToTable("Organizer");

                    b.HasDiscriminator().HasValue("Organizer");
                });

            modelBuilder.Entity("ConFutureNce.Models.ProgrammeCommitteeMember", b =>
                {
                    b.HasBaseType("ConFutureNce.Models.UserType");

                    b.Property<string>("EmployeePosition")
                        .HasColumnName("ProgrammeCommitteeMember_EmployeePosition");

                    b.ToTable("ProgrammeCommitteeMember");

                    b.HasDiscriminator().HasValue("ProgrammeCommitteeMember");
                });

            modelBuilder.Entity("ConFutureNce.Models.Reviewer", b =>
                {
                    b.HasBaseType("ConFutureNce.Models.UserType");

                    b.Property<int>("Language1Id");

                    b.Property<int?>("Language2Id");

                    b.Property<int?>("Language3Id");

                    b.Property<string>("OrgName")
                        .HasColumnName("Reviewer_OrgName");

                    b.Property<string>("ScTitle")
                        .HasColumnName("Reviewer_ScTitle");

                    b.HasIndex("Language1Id");

                    b.HasIndex("Language2Id");

                    b.HasIndex("Language3Id");

                    b.ToTable("Reviewer");

                    b.HasDiscriminator().HasValue("Reviewer");
                });

            modelBuilder.Entity("ConFutureNce.Models.ApplicationUser", b =>
                {
                    b.HasOne("ConFutureNce.Models.Conference", "Conference")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("ConferenceName")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConFutureNce.Models.Invoice", b =>
                {
                    b.HasOne("ConFutureNce.Models.Payment", "Payment")
                        .WithOne("Invoice")
                        .HasForeignKey("ConFutureNce.Models.Invoice", "PaymentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConFutureNce.Models.Paper", b =>
                {
                    b.HasOne("ConFutureNce.Models.Author", "Author")
                        .WithMany("Papers")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConFutureNce.Models.Language", "Language")
                        .WithMany("Papers")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConFutureNce.Models.Reviewer", "Reviewer")
                        .WithMany("Papers")
                        .HasForeignKey("ReviewerId");
                });

            modelBuilder.Entity("ConFutureNce.Models.PaperKeyword", b =>
                {
                    b.HasOne("ConFutureNce.Models.Paper", "Paper")
                        .WithMany("PaperKeywords")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConFutureNce.Models.Payment", b =>
                {
                    b.HasOne("ConFutureNce.Models.Paper", "Paper")
                        .WithOne("Payment")
                        .HasForeignKey("ConFutureNce.Models.Payment", "PaperId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConFutureNce.Models.Review", b =>
                {
                    b.HasOne("ConFutureNce.Models.Paper", "Paper")
                        .WithOne("Review")
                        .HasForeignKey("ConFutureNce.Models.Review", "PaperId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConFutureNce.Models.UserType", b =>
                {
                    b.HasOne("ConFutureNce.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Users")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ConFutureNce.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ConFutureNce.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConFutureNce.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ConFutureNce.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConFutureNce.Models.Reviewer", b =>
                {
                    b.HasOne("ConFutureNce.Models.Language", "Language1")
                        .WithMany("ReviewersFirst")
                        .HasForeignKey("Language1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ConFutureNce.Models.Language", "Language2")
                        .WithMany("ReviewersSecond")
                        .HasForeignKey("Language2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ConFutureNce.Models.Language", "Language3")
                        .WithMany("ReviewersThird")
                        .HasForeignKey("Language3Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
